import type { Metadata } from "next";
import { Urbanist} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import clsx from "clsx";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-800 text-slate-100">
      <body className={clsx(urbanist.className, "relative min-h-screen")}>
        <Header/>
        {children}
        </body>
    </html>
  );
}
